# Generated by Django 5.1.7 on 2025-03-21 22:27

from django.db import migrations

def create_sample_exercises(apps, schema_editor):
    Exercise = apps.get_model('exercises', 'Exercise')
    
    exercises = [
        {
            'name': 'Push-up',
            'description': 'A classic upper body exercise that targets chest, shoulders, and triceps.',
            'image_url': 'https://example.com/pushup.jpg',
            'difficulty': 'beginner'
        },
        {
            'name': 'Squat',
            'description': 'A fundamental lower body exercise that targets legs and glutes.',
            'image_url': 'https://example.com/squat.jpg',
            'difficulty': 'beginner'
        },
        {
            'name': 'Arm Raises',
            'description': 'A shoulder exercise that improves upper body strength and mobility.',
            'image_url': 'https://example.com/armraises.jpg',
            'difficulty': 'beginner'
        },
        {
            'name': 'Plank',
            'description': 'A core exercise that helps build stability and endurance.',
            'image_url': 'https://example.com/plank.jpg',
            'difficulty': 'intermediate'
        },
        {
            'name': 'Jumping Jack',
            'description': 'A full-body cardio exercise that improves coordination and cardiovascular fitness.',
            'image_url': 'https://example.com/jumpingjack.jpg',
            'difficulty': 'intermediate'
        }
    ]
    
    for exercise_data in exercises:
        Exercise.objects.create(**exercise_data)

def remove_sample_exercises(apps, schema_editor):
    Exercise = apps.get_model('exercises', 'Exercise')
    Exercise.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_sample_exercises, remove_sample_exercises),
    ]
