# Generated by Django 5.1.7 on 2025-03-21 22:41

from django.db import migrations, models

def update_exercises(apps, schema_editor):
    Exercise = apps.get_model('exercises', 'Exercise')
    
    # Update existing exercises with EXP values
    exercises = {
        'Push-up': 5,
        'Squat': 5,
        'Arm Raises': 3,
        'Plank': 4,
        'Jumping Jack': 4
    }
    
    for name, exp in exercises.items():
        Exercise.objects.filter(name=name).update(exp_per_rep=exp)

def reverse_exercises(apps, schema_editor):
    Exercise = apps.get_model('exercises', 'Exercise')
    Exercise.objects.all().update(exp_per_rep=0)

class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20250321_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exp_per_rep',
            field=models.IntegerField(default=0, help_text='Experience points earned per repetition'),
        ),
        migrations.RunPython(update_exercises, reverse_exercises),
    ]
