# Generated by Django 5.1.7 on 2025-03-21 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20250321_1924'),
        ('exercises', '0003_auto_20250321_2241'),
    ]

    operations = [
    ]
